
server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

spring:
  datasource:
    password: rhgPdus00@!
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BlogProject?serverTimezone=Asia/Seoul
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    open-in-view: false

jpa:
  open-in-view: false
  hibernate:
    ddl-auto: create
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    use-new-id-generator-mappings: false
  show-sql: true
  properties:
    hibernate.format_sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false