
server:
  port: 8085

spring:
  datasource:
    password: rhgPdus00@!
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BlogProject?serverTimezone=Asia/Seoul

